version: "3"

services:
    app:
        # https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php.html
        build: ./
        ports:
            - 8080:8080
        working_dir: /app
        environment: 
            - PHP_MEMORY_LIMIT=512M
            - PHP_MAX_EXECUTION_TIME=30
            - PHP_POST_MAX_SIZE=20M
            - PHP_UPLOAD_MAX_FILESIZE=20M
            - XDEBUG_MODE=coverage
        volumes:
            - './:/app'